### ISSUE TITLE
60 KB of moment.js in my final bundle

### ISSUE THREAD

**Issue by carmelone** [Marketto/belfiore-connector#27]
Is there a way to avoid ~ 60 KB of moment.js?

![image](https://github.com/user-attachments/assets/bea5c3ea-4fa8-4d1d-8b4b-aa3c4e81293a)

Do we really need it?

**Comment by Marketto** [comment]
I'll give a look for the next release

**Comment by carmelone** [comment]
I think we can remove it totally using Javascript Date with new Intl.DateTimeFormat APIs.

**Comment by Marketto** [comment]
Solved with v. 3.0.0
